
require 'database_cleaner'
# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

RSpec.configure do |config|
  config.before(:suite) do
      # Truncate database to clean up garbage from 
      # interrupted or badly written examples
      DatabaseCleaner.clean_with(:truncation)

      # Seed dataase. Use it only for essential
      # to run application data.
      load "#{Rails.root}/db/seeds.rb"
    end

    config.around(:each) do |example|
      # Use really fast transaction strategy for all 
      # examples except `js: true` capybara specs
      DatabaseCleaner.strategy = example.metadata[:js] ? :truncation : :transaction

      # Start transaction
      DatabaseCleaner.start

      # Run example
      example.run

      # Rollback transaction
      DatabaseCleaner.clean

      # Clear session data
      Capybara.reset_sessions!
  end
end
